blog/urls.py
from django.urls import path

from .views import (
    index,
    add_post,
    BlogUserCreateView,
    add_comment,
    add_reply,
    delete_post,
    delete_comment,
    delete_reply,
    edit_post,
    edit_comment,
    edit_reply,
)

urlpatterns = [
    path("", index, name="index"),
    path("create_posts/", add_post, name="add_post"),
    path("user/create/", BlogUserCreateView.as_view(), name="user_create"),
    path("create_comment/<int:post_id>", add_comment, name="add_comment"),
    path("create_reply/<int:comment_id>", add_reply, name="add_reply"),
    path("delete_post/<int:post_id>", delete_post, name="delete_post"),
    path("delete_comment/<int:comment_id>", delete_comment, name="delete_comment"),
    path("delete_reply/<int:reply_id>", delete_reply, name="delete_reply"),
    path("edit_post/<int:post_id>/", edit_post, name="edit_post"),
    path("edit_comment/<int:comment_id>/", edit_comment, name="edit_comment"),
    path("edit_reply/<int:reply_id>/", edit_reply, name="edit_reply"),
]

app_name = "blog"

posts_and_comments/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("captcha/", include("captcha.urls")),
    path("", include("blog.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
]

blog/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models

from django_ckeditor_5.fields import CKEditor5Field


class BlogUser(AbstractUser):
    pass


class CreateMessage(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="%(class)s_messages",
    )
    text = CKEditor5Field(config_name="extends")
    created_at = models.DateTimeField(auto_now_add=True)

    def formatted_date(self):
        return self.created_at.strftime("%d.%m.%Y %H:%M")

    def __str__(self):
        return f"{self.created_at} ---- {self.user.username} ---- {self.user.email}"

    class Meta:
        abstract = True
        ordering = ("created_at",)


class Post(CreateMessage):
    pass


class Comment(CreateMessage):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments",
    )


class Reply(CreateMessage):
    comment = models.ForeignKey(
        Comment,
        on_delete=models.CASCADE,
        related_name="replies",
    )

    class Meta:
        verbose_name_plural = "Replies"

blog/forms.py
from django import forms
from captcha.fields import CaptchaField
from django.contrib.auth.forms import UserCreationForm

from .models import Post, BlogUser, Comment, Reply

from django_ckeditor_5.widgets import CKEditor5Widget

SORT_CHOICES = [
    ("username", "Username"),
    ("email", "Email"),
    ("created_at", "Created at"),
]

ORDER_CHOICES = [
    ("asc", "Ascending"),
    ("desc", "Descending"),
]


class BlogUserCreateForm(UserCreationForm):

    class Meta:
        model = BlogUser
        fields = ["username", "email", "password1", "password2"]


class PostCreateForm(forms.ModelForm):
    username = forms.CharField(
        max_length=255,
        label="Username",
    )
    email = forms.EmailField(label="Email")
    captcha = CaptchaField(label="Captcha", help_text="Enter the captcha")

    class Meta:
        model = Post
        fields = ["text"]
        widgets = {
            "text": CKEditor5Widget(
                attrs={"class": "django_ckeditor_5"}, config_name="comment"
            )
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ["text"]
        widgets = {
            "text": CKEditor5Widget(
                attrs={"class": "django_ckeditor_5"}, config_name="comment"
            )
        }


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ["text"]
        widgets = {
            "text": CKEditor5Widget(
                attrs={"class": "django_ckeditor_5"}, config_name="comment"
            )
        }


class CommentsSortForm(forms.Form):
    sort_by = forms.ChoiceField(
        choices=SORT_CHOICES,
        required=False,
        label="Sort by",
    )
    order = forms.ChoiceField(
        choices=ORDER_CHOICES,
        required=False,
        label="Order",
    )


class PostEditForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ["text"]
        widgets = {
            "text": CKEditor5Widget(
                attrs={"class": "django_ckeditor_5"}, config_name="comment"
            )
        }

blog/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Prefetch
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .models import Post, BlogUser, Comment, Reply
from .forms import (
    PostCreateForm,
    BlogUserCreateForm,
    CommentForm,
    ReplyForm,
    CommentsSortForm,
    PostEditForm,
)
from .utils import clean_and_validate_html


def index(request):
    sort_by = request.GET.get("sort_by", "created_at")
    order = request.GET.get("order", "asc")

    sort_order = "" if order == "asc" else "-"

    if sort_by == "username":
        sort_by = "user__username"
    elif sort_by == "email":
        sort_by = "user__email"
    else:
        sort_by = "created_at"

    comments_prefetch = Prefetch(
        "comments",
        queryset=Comment.objects.select_related("user").prefetch_related("replies"),
    )

    posts = (
        Post.objects.all()
        .select_related("user")
        .prefetch_related(comments_prefetch)
        .order_by(f"{sort_order}{sort_by}")
    )

    paginator = Paginator(posts, 5)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    form = CommentsSortForm(request.GET or None)

    context = {
        "page_obj": page_obj,
        "form": form,
    }

    return render(request, "blog/index.html", context)


@login_required
def add_post(request):
    if request.method == "POST":
        form = PostCreateForm(request.POST)
        if form.is_valid():
            user_name = form.cleaned_data.get("username")
            user_email = form.cleaned_data.get("email")

            if user_name != request.user.username or user_email != request.user.email:
                form.add_error(None, "Name or email doesn't match with your account.")
            else:
                post_text = form.cleaned_data.get("text")

                if post_text:
                    cleaned_text = clean_and_validate_html(post_text)
                    if cleaned_text:
                        post = form.save(commit=False)
                        post.user = request.user
                        post.text = cleaned_text
                        post.save()
                        return redirect("blog:index")
                    else:
                        form.add_error(None, "Your content contains invalid HTML tags.")
                else:
                    form.add_error("text", "Content cannot be empty.")
    else:
        form = PostCreateForm()

    return render(request, "blog/create_post.html", {"form": form})


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_text = form.cleaned_data.get("text")
            cleaned_text = clean_and_validate_html(comment_text)
            if cleaned_text:
                comment = form.save(commit=False)
                comment.user = request.user
                comment.post = post
                comment.text = cleaned_text
                comment.save()
                return redirect("blog:index")
            else:
                form.add_error(None, "Your comment contains invalid HTML tags.")
    else:
        form = CommentForm()

    return render(
        request,
        "blog/create_comment.html",
        {"form": form, "post": post},
    )


@login_required
def add_reply(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)

    if request.method == "POST":
        form = ReplyForm(request.POST)
        if form.is_valid():
            reply_text = form.cleaned_data.get("text")
            cleaned_text = clean_and_validate_html(reply_text)
            if cleaned_text:
                reply = form.save(commit=False)
                reply.user = request.user
                reply.comment = comment
                reply.text = cleaned_text
                reply.save()
                return redirect("blog:index")
            else:
                form.add_error(None, "Your reply contains invalid HTML tags.")
    else:
        form = ReplyForm()

    return render(
        request,
        "blog/create_reply.html",
        {"form": form, "comment": comment},
    )


class BlogUserCreateView(CreateView):
    user = BlogUser
    form_class = BlogUserCreateForm
    template_name = "blog/user_form.html"
    success_url = reverse_lazy("blog:index")


@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.user:
        return HttpResponseForbidden("You do not have permission to delete this post.")

    if request.method == "POST":
        post.delete()
        return redirect("blog:index")
    return render(request, "blog/delete_post.html", {"post": post})


@login_required
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if request.user != comment.user:
        return HttpResponseForbidden(
            "You do not have permission to delete this comment."
        )

    if request.method == "POST":
        comment.delete()
        return redirect("blog:index")
    return render(request, "blog/delete_comment.html", {"comment": comment})


@login_required
def delete_reply(request, reply_id):
    reply = get_object_or_404(Reply, id=reply_id)
    if request.user != reply.user:
        return HttpResponseForbidden("You do not have permission to delete this reply.")

    if request.method == "POST":
        reply.delete()
        return redirect("blog:index")
    return render(request, "blog/delete_reply.html", {"reply": reply})


@login_required
def edit_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    if request.user != post.user:
        return redirect("blog:index")

    if request.method == "POST":
        form = PostEditForm(request.POST, instance=post)
        if form.is_valid():
            post_text = form.cleaned_data.get("text")
            cleaned_text = clean_and_validate_html(post_text)
            if cleaned_text:
                post.text = cleaned_text
                form.save()
                return redirect("blog:index")
            else:
                form.add_error(None, "Your content contains invalid HTML tags.")
    else:
        form = PostEditForm(instance=post)

    return render(request, "blog/edit_post.html", {"form": form})


@login_required
def edit_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)

    if request.user != comment.user:
        return redirect("blog:index")

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment_text = form.cleaned_data.get("text")
            cleaned_text = clean_and_validate_html(comment_text)
            if cleaned_text:
                comment.text = cleaned_text
                form.save()
                return redirect("blog:index")
            else:
                form.add_error(None, "Your comment contains invalid HTML tags.")
    else:
        form = CommentForm(instance=comment)

    return render(request, "blog/edit_comment.html", {"form": form})


@login_required
def edit_reply(request, reply_id):
    reply = get_object_or_404(Reply, id=reply_id)

    if request.user != reply.user:
        return redirect("blog:index")

    if request.method == "POST":
        form = ReplyForm(request.POST, instance=reply)
        if form.is_valid():
            reply_text = form.cleaned_data.get("text")
            cleaned_text = clean_and_validate_html(reply_text)
            if cleaned_text:
                reply.text = cleaned_text
                form.save()
                return redirect("blog:index")
            else:
                form.add_error(None, "Your reply contains invalid HTML tags.")
    else:
        form = ReplyForm(instance=reply)

    return render(request, "blog/edit_reply.html", {"form": form})

templates/blog/create_comment.html
{% extends "base.html" %}

{% block content %}
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% endblock %}

templates/blog/create_post.html
{% extends "base.html" %}

{% block content %}
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% endblock %}

templates/blog/create_reply.html
{% extends "base.html" %}

{% block content %}
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% endblock %}

templates/blog/delete_comment.html
<p class="delete-link">
  <a href="{% url 'blog:delete_comment' comment.id %}">Delete comment</a>
</p>

templates/blog/delete_post.html
<p class="delete-link">
  <a href="{% url 'blog:delete_post' post.id %}">Delete post</a>
</p>

templates/blog/delete_reply.html
<p class="delete-link">
  <a href="{% url 'blog:delete_reply' comment.id %}">Delete reply</a>
</p>

templates/blog/edit_blog.html
{% extends "base.html" %}

{% block content %}
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Edit</button>
  </form>
{% endblock %}

templates/blog/edit_comment.html
{% extends "base.html" %}

{% block content %}
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <button type="submit">Edit</button>
  </form>
{% endblock %}

templates/blog/edit_post.html
{% extends "base.html" %}

{% block content %}
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <button type="submit">Edit</button>
  </form>
{% endblock %}

templates/blog/edit_reply.html
{% extends "base.html" %}

{% block content %}
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <button type="submit">Edit</button>
  </form>
{% endblock %}

templates/blog/index.html
{% extends "base.html" %}

{% block content %}
  <form method="get" class="filter-form">
    <label for="sort_by">{{ form.sort_by.label }}</label>
    {{ form.sort_by }}

    <label for="order">{{ form.order.label }}</label>
    {{ form.order }}

    <button type="submit">Sort</button>
  </form>
  {% if page_obj %}
    {% for post in page_obj %}
      <div class="message">
        <div class="post-info">
          <p class="user-name">{{ post.user.username }}</p>
          <p class="date-info">{{ post.formatted_date }}</p>
        </div>
        <p class="text-area">{{ post.text|safe }}</p>
        <div class="edition">
          {% if request.user == post.user %}

            <div class="editing-group">
              <form method="post" action="{% url 'blog:delete_post' post.id %}">
                {% csrf_token %}
                <button type="submit" class="delete-btn">Delete</button>
              </form>
              <p>
                <a href="{% url 'blog:edit_post' post.id %}">Edit</a>
              </p>
            </div>
          {% endif %}
          <p class="add-message">
            <a href="{% url "blog:add_comment" post_id=post.id %}">Comment</a>
          </p>
        </div>

      </div>
      <br>

      {% if post.comments %}
        <br>
        <div class="comments-container">
          {% for comment in post.comments.all %}
            <div class="comment">
              <div class="post-info">
                <p class="user-name">{{ comment.user.username }}</p>
                <p class="date-info">{{ comment.formatted_date }}</p>
              </div>
              <p class="text-area">{{ comment.text|safe }}</p>
              <div>
                <div class="edition">
                  {% if request.user == comment.user %}
                    <div class="editing-group">
                      <form method="post" action="{% url 'blog:delete_comment' comment.id %}">
                        {% csrf_token %}
                        <button type="submit" class="delete-btn">Delete</button>
                      </form>
                      <p>
                        <a href="{% url 'blog:edit_comment' comment.id %}">Edit</a>
                      </p>
                    </div>
                  {% endif %}
                  <p class="comment-link">
                    <a class="comment-link-btn" href="{% url "blog:add_reply" comment_id=comment.id %}">Comment</a>
                  </p>
                </div>

              </div>
            </div>
            <br>

            {% if comment.replies %}
              {% for reply in comment.replies.all %}
                <div class="reply">
                  <div class="post-info">
                    <p class="user-name">{{ reply.user.username }}</p>
                    <p class="date-info">{{ reply.formatted_date }}</p>
                  </div>
                  <p class="text-area">{{ reply.text|safe }}</p>

                  {% if request.user == reply.user %}
                    <div class="editing-group">
                      <form method="post" action="{% url 'blog:delete_reply' reply.id %}">
                        {% csrf_token %}
                        <button type="submit" class="delete-btn">Delete</button>
                      </form>
                      <p>
                        <a href="{% url 'blog:edit_reply' reply.id %}">Edit</a>
                      </p>
                    </div>
                  {% endif %}
                </div>
                <br>
              {% endfor %}
            {% endif %}
          {% endfor %}
        </div>
      {% endif %}
    {% endfor %}
    <div class="pagination">
      <span class="step-links">
        {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
      </span>
    </div>
  {% endif %}
{% endblock %}

templates/blog/user_form.html
{% extends "base.html" %}

{% block content %}

<section class="section" id="createUser">
  <div class="container">
    <div class="row">
      <div class="col-lg">
        <h1>Create User</h1>
        <form action="" method="post" novalidate>
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Submit" class="btn btn-primary">
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}